services:
  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-cid", "orders-cluster", "-p", "4222", "-m", "8222"]
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: orders-db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d orders-db"]
  orders-service:
    build: ./
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"

